server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: abc@123 # Use your real password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ThisIsAVeryLongAndSecureSecretKeyForYourChatApplicationPleaseChangeIt
  expiration-ms: 86400000
